events { worker_connections 1024; }

http {
    upstream agenda_hub {
        server ms-agenda-hub:8080;
    }

    upstream insurance {
        server ms-insurance:8081;
    }

    server {
        listen 80;

        # MS-AgendaHub: entry point principal
        location /appointments {
            proxy_pass         http://agenda_hub;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Request-ID $request_id;
        }

        location /slots {
            proxy_pass http://agenda_hub;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://agenda_hub;
        }
    }
}
